apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-backup
spec:
  schedule: "0 7 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-backup
            image: appropriate/curl
            args:
            - /bin/sh
            - -c
            - curl -X PUT "http://elasticsearch-master:9200/_snapshot/aws-s3-es-log-kibana-dev/snapshot_$(date +%d%m%y-%H%M%S)?wait_for_completion=true&pretty"
          restartPolicy: OnFailure

          curl -X PUT "localhost:9200/_slm/policy/nightly-snapshots?pretty" -H 'Content-Type: application/json' -d'
          {
            "schedule": "0 6 * * 1", 
            "name": "<weekly-snap-{now/d}>", 
            "repository": "aws-s3-es-log-kibana-dev", 
            "config": { 
              "indices": ["*"] 
            },
            "retention": { 
              "expire_after": "90d", 
              "min_count": 5 
            }
          }
          '
          